// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using chefeia.Data;

#nullable disable

namespace chefeia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260826195117_CriarControleConsumoIA")]
    partial class CriarControleConsumoIA
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("chefeia.Models.AiUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreditLimit")
                        .HasColumnType("integer");

                    b.Property<int?>("CreditRemaining")
                        .HasColumnType("integer");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("IngredientCount")
                        .HasColumnType("integer");

                    b.Property<string>("PlanName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Preference")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("RequestsLimit")
                        .HasColumnType("integer");

                    b.Property<int?>("RequestsRemaining")
                        .HasColumnType("integer");

                    b.Property<int>("Servings")
                        .HasColumnType("integer");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Success");

                    b.HasIndex("UserId");

                    b.ToTable("AiUsages");
                });

            modelBuilder.Entity("chefeia.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("HasAds")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MonthlyAiLimit")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("chefeia.Models.SiteSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Feature1Emoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Feature1Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Feature1Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Feature2Emoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Feature2Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Feature2Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Feature3Emoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Feature3Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Feature3Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Feature4Emoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Feature4Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Feature4Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeaturedRecipeCountry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeaturedRecipeImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FeaturedRecipeMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("FeaturedRecipeServings")
                        .HasColumnType("integer");

                    b.Property<string>("FeaturedRecipeTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FreeMonthlyLimit")
                        .HasColumnType("integer");

                    b.Property<string>("HeroImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeroSubtitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeroTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PremiumMonthlyLimit")
                        .HasColumnType("integer");

                    b.Property<decimal>("PremiumPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("SearchPlaceholder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteSlogan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Feature1Emoji = "🥗",
                            Feature1Text = "Criadas sob medida com os ingredientes que você tem.",
                            Feature1Title = "Receitas personalizadas",
                            Feature2Emoji = "⏱️",
                            Feature2Text = "Receitas prontas em segundos para facilitar seu dia.",
                            Feature2Title = "Rápido e prático",
                            Feature3Emoji = "🌎",
                            Feature3Text = "Explore sabores de diferentes países e culturas.",
                            Feature3Title = "Cozinha do mundo",
                            Feature4Emoji = "❤️",
                            Feature4Text = "Descubra novas combinações e experiências.",
                            Feature4Title = "Feito com carinho",
                            FeaturedRecipeCountry = "Brasileira",
                            FeaturedRecipeImageUrl = "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d",
                            FeaturedRecipeMinutes = 35,
                            FeaturedRecipeServings = 4,
                            FeaturedRecipeTitle = "Frango Cremoso com Batatas",
                            FreeMonthlyLimit = 3,
                            HeroImageUrl = "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d",
                            HeroSubtitle = "Digite os ingredientes que você tem em casa e deixe o Chefe IA criar algo incrível para você!",
                            HeroTitle = "Sua próxima receita começa aqui",
                            PremiumMonthlyLimit = 50,
                            PremiumPrice = 39.90m,
                            SearchPlaceholder = "Ex: frango, batata, tomate...",
                            SiteName = "Chefe IA",
                            SiteSlogan = "Receitas que surpreendem!"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
